version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs-dev-app
    volumes:
      # Mount source code for hot reloading
      - .:/app
      # Prevent overwriting node_modules
      - /app/node_modules
      # Mount fish config to persist changes
      - fish_config:/root/.config/fish
    environment:
      - NODE_ENV=development
      - SHELL=/usr/bin/fish
    # Keep container running for development
    tty: true
    stdin_open: true
    # Keep container alive without starting dev server
    command: fish -c "sleep infinity"

volumes:
  fish_config:
